tenant: ac360 # Enter your tenant name here
app: demos # Enter your application name here
service: fullstack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  environment:
    foo: ${secrets:foo}

functions:
  formSubmit:
    handler: index.submit
    events:
      - http:
          path: submit
          method: post
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: demo-fullstack-89aja9j # Change this to a universally unique bucket name
    distributionFolder: ../frontend/build
